// import './globals.css'
import { Providers } from "./redux/provider"
// importing Providers component inside of the layout component lets the entire app, as well as nested components, use the redux store

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
        
      </body>
    </html>
  )
}
